version: '2'
services:
  server:
    image: pms
    ports:
    - "8080:8080"
    depends_on:
    - postgres
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres